# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f7b39a900a0175a962a8d24457d85a77ee58efd3a6489266a38c3ddf30f20a711265a6252a90d3f2b3b6a0bc1923c49b4381d64e06bb99bd527b14b3c7b16ec

test:
  secret_key_base: 03a4b16c491fec9ff02bc894df5a2a2b36ef8c5ff5d600306c6d59f813871f8096cd58cf145ad56d28b9ddff5303b6ad939d91de5367faac0e3006caf9c0c2ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
